name: Ubuntu (ngrok)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Start Script
      run: source ubuntu-start.sh

    - name: Install Latest ngrok
      run: |
        NGROK_ZIP=$(curl -s https://api.github.com/repos/ngrok/ngrok/releases/latest \
          | grep "browser_download_url.*linux-amd64.zip" \
          | cut -d '"' -f 4)
        curl -L "$NGROK_ZIP" -o ngrok.zip
        unzip ngrok.zip -d ngrok-bin
        sudo mv ngrok-bin/ngrok /usr/local/bin/ngrok
        ngrok version  # Verify installation

    - name: Start SSH via ngrok
      uses: rdp-studio/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: eu
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run End Script
      run: source ubuntu-end.sh
