name: Ubuntu (ngrok)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Start Script
      run: source ubuntu-start.sh

    - name: Install ngrok (Direct)
      run: |
        curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -o ngrok.tgz
        tar -xvzf ngrok.tgz
        sudo mv ngrok /usr/local/bin/ngrok
        chmod +x /usr/local/bin/ngrok
        ngrok version

    - name: Start SSH via ngrok
      uses: rdp-studio/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: eu
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run End Script
      run: source ubuntu-end.sh
